-- +goose Up
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL
);

ALTER TABLE UrlReferences ADD ownedBy INTEGER NOT NULL;

DROP TABLE UrlReferences;

CREATE TABLE IF NOT EXISTS UrlReferences (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			originalUrl TEXT NOT NULL,
			short_code TEXT NOT NULL UNIQUE,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
